### ISSUE TITLE
CS0108: 'App.Logger' hides inherited member 'PrismApplication.Logger'. Use the new keyword if hiding was intended.

### ISSUE THREAD

**Issue by SeriousM** [dansiegel/Prism.Magician.Docs#5]
Versions:
Prism.Magican 8.1.9
Prism.DryIoc.Extensions 8.0.67

My app is inheriting from `Prism.PrismApplication` and the generated code from magican is generating a partial class that defines the `Logger` property.
The problem is that PrismApplication is already offering the `Logger` property which leads to this error:

`'App.Logger' hides inherited member 'PrismApplication.Logger'. Use the new keyword if hiding was intended.`

PrismApplication code:
```cs
public ILogger Logger { get; private set; }
```

Magican generated code:
```cs
private Prism.Logging.ILogger _logger;

[GeneratedCodeAttribute("AbracadabraGenerator", "8.1.9+91b82caa14")]
public Prism.Logging.ILogger Logger
{
    get
    {
        if (_logger is null)
        {
            _logger = Container.Resolve<ILogger>();
        }

        return _logger;
    }
}
```

**Comment by dansiegel** [comment]
The Magician is not meant to be used with the Prism Container Extensions, it replaces it. Please use the official Prism packages instead.
