### ISSUE TITLE
[Enhancement] Constructor Services for lazy people

### ISSUE THREAD

**Issue by Codelisk** [dansiegel/Prism.Magician.Docs#7]
Don't know whether thats possible or even a good thing to do, however what i have in mind is the following:

in nearly every viewmodel or service we have something like this:

```
private readonly IService _service1;

public Constructor(IService service1)
{
this._service1 = service1 ?? throw new ArgumentNullException(nameof(service1));
}
```

Maby it would be possible to make it look somewhat like this:

```
[Service(typeof(IService))]
public Constructor() {}
```
or
`public Constructor([Service<IService>]) {}`

**Comment by SeriousM** [comment]
I guess you talk about property / field injection.

I use a system where I mark a property with a property and the IoC is injecting the services where I want:
```
[Import]
public IService ServiceName {get;set;}
```

works well and I can define the name of the property myself.

**Comment by Codelisk** [comment]
Oh thats amazing thank you
