### ISSUE TITLE
[Enhancement] Magician Snippets

### ISSUE THREAD

**Issue by Codelisk** [dansiegel/Prism.Magician.Docs#8]
It would be nice to have Snippets for the magican :)

Especially for:

```
[BindableProperty]
public object objectname { get; set; }
```

```
[Bindable]
public object objectname { get; set; }
```

**Comment by dansiegel** [comment]
@Codelisk not sure what exactly you're looking for? Like what each transforms into?

**Comment by Codelisk** [comment]
Closed, dont see too much time saving for that idea :)
